const questions = [
    {
        "question": "Welcher Baum ist in Mitteleuropa am weitesten verbreitet?",
        "answer_1": "Buche",
        "answer_2": "Eiche",
        "answer_3": "Fichte",
        "answer_4": "Kiefer",
        "right_answer": "3",
    },
    {
        "question": "Wie nennt man eine Gruppe von Wölfen?",
        "answer_1": "Rudel",
        "answer_2": "Herde",
        "answer_3": "Schwarm",
        "answer_4": "Kolonie",
        "right_answer": "1",
    },
    {
        "question": "Welches Tier hält keinen Winterschlaf?",
        "answer_1": "Igel",
        "answer_2": "Eichhörnchen",
        "answer_3": "Dachs",
        "answer_4": "Fledermaus",
        "right_answer": "2",
    },
    {
        "question": "Welches Tier ist das größte lebende Säugetier der Erde?",
        "answer_1": "Afrikanischer Elefant",
        "answer_2": "Blauwal",
        "answer_3": "Pottwal",
        "answer_4": "Giraffe",
        "right_answer": "2",
    },
    {
        "question": "Wie nennt man den Punkt, an dem ein Stern explodiert?",
        "answer_1": "Asteroid",
        "answer_2": "Meteor",
        "answer_3": "Quasar",
        "answer_4": "Supernova",
        "right_answer": "4",
    },
    {
        "question": "Welcher Planet ist der Sonne am nächsten?",
        "answer_1": "Venus",
        "answer_2": "Merkur",
        "answer_3": "Mars",
        "answer_4": "Erde",
        "right_answer": "2",
    },
    {
        "question": "Wie nennt man Wälder, die dauerhaft nass und artenreich sind?",
        "answer_1": "Regenwälder",
        "answer_2": "Nadelwälder",
        "answer_3": "Laubwälder",
        "answer_4": "Mangrovenwälder",
        "right_answer": "1",
    },
    {
        "question": "Welches Tier baut Dämme aus Ästen und Holz?",
        "answer_1": "Dachs",
        "answer_2": "Otter",
        "answer_3": "Biber",
        "answer_4": "Waschbär",
        "right_answer": "3",
    },
    {
        "question": "Welches Tier kann rückwärts fliegen?",
        "answer_1": "Kolibri",
        "answer_2": "Fledermaus",
        "answer_3": "Schwalbe",
        "answer_4": "Libelle",
        "right_answer": "1",
    },
    {
        "question": "Wie heißt der größte Kontinent der Erde?",
        "answer_1": "Afrika",
        "answer_2": "Asien",
        "answer_3": "Europa",
        "answer_4": "Nordamerika",
        "right_answer": "2",
    }
];