const questions = [
    {
        "question": "Welcher Baum ist in Mitteleuropa am weitesten verbreitet?",
        "answer_1": "Buche",
        "answer_2": "Eiche",
        "answer_3": "Fichte",
        "answer_4": "Kiefer",
        "right_answer": "3",
    },
    {
        "question": "Wie nennt man eine Gruppe von Wölfen?",
        "answer_1": "Rudel",
        "answer_2": "Herde",
        "answer_3": "Schwarm",
        "answer_4": "Kolonie",
        "right_answer": "1",
    },
    {
        "question": "Welches Tier hält keinen Winterschlaf?",
        "answer_1": "Igel",
        "answer_2": "Eichhörnchen",
        "answer_3": "Dachs",
        "answer_4": "Fledermaus",
        "right_answer": "2",
    },
    {
        "question": "Welches Tier ist das größte lebende Säugetier der Erde?",
        "answer_1": "Afrikanischer Elefant",
        "answer_2": "Blauwal",
        "answer_3": "Pottwal",
        "answer_4": "Giraffe",
        "right_answer": "2",
    },
    {
        "question": "Wie nennt man den Punkt, an dem ein Stern explodiert?",
        "answer_1": "Supernova",
        "answer_2": "Meteor",
        "answer_3": "Quasar",
        "answer_4": "Asteroid",
        "right_answer": "1",
    },
    {
        "question": "Welcher Planet ist der Sonne am nächsten?",
        "answer_1": "Venus",
        "answer_2": "Merkur",
        "answer_3": "Mars",
        "answer_4": "Erde",
        "right_answer": "2",
    }
];